/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const BillingInfo = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'items' : IDL.Vec(OrderItem),
  'billingInfo' : BillingInfo,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});
export const ContactId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : ContactId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), BillingInfo, IDL.Float64],
      [Order],
      [],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'seedProducts' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
  'upsertProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfilePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const BillingInfo = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'items' : IDL.Vec(OrderItem),
    'billingInfo' : BillingInfo,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const ContactId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : ContactId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), BillingInfo, IDL.Float64],
        [Order],
        [],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedProducts' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'upsertProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfilePublic], []),
  });
};

export const init = ({ IDL }) => { return []; };