/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingInfo {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'email' : string,
  'address' : string,
}
export type ContactId = bigint;
export interface ContactMessage {
  'id' : ContactId,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'items' : Array<OrderItem>,
  'billingInfo' : BillingInfo,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : number,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'email' : string,
}
export interface _SERVICE {
  'createOrder' : ActorMethod<[Array<OrderItem>, BillingInfo, number], Order>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listProducts' : ActorMethod<[[] | [string], [] | [string]], Array<Product>>,
  'seedProducts' : ActorMethod<[], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    ContactMessage
  >,
  'upsertProfile' : ActorMethod<[string, string], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];